services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - finkeith_network

  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "10001:10001"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - finkeith_network

networks:
  finkeith_network:
    driver: bridge

volumes:
  finkeith_data: